### ISSUE TITLE
Error compiling a sample

### ISSUE THREAD

**Issue by iQuarK** [maxzerbini/oauth#1]
I get 
`
vendor/github.com/maxzerbini/oauth/server.go:247:23: multiple-value uuid.NewV4() in single-value context`
`vendor/github.com/maxzerbini/oauth/server.go:258:52: multiple-value uuid.NewV4() in single-value context`

When I try to build :(

**Comment by maxzerbini** [comment]
Hi @iQuarK ,

this error depends on the last update of the satori library that changes the signature of the NewV4() method. Unfortunately the go.uuid lib is not versioned in branches.
I will update oauth code soon.

**Comment by maxzerbini** [comment]
Fix done.

**Comment by iQuarK** [comment]
thanks :) (sorry for the late response)
